[build]
  command = "pnpm install && pnpm build"
  publish = "dist"

[dev]
  command = "pnpm dev"
  targetPort = 3000
  port = 8888
  autoLaunch = false

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["data/**"]

[[redirects]]
  from = "/"
  to = "https://github.com/Sasivarnasarma/Readme-Thirukkural"
  status = 302

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
